### ISSUE TITLE
mysql.py. suffix in _version may not be an integer value ==> error

### ISSUE THREAD

**Issue by PatrickBzh** [ansible-collections/community.proxysql#93]
##### SUMMARY
in mysql.py::_version suffix variable may not be an integer value
example: With  Percona's proxysql :

```
mysql> select version();
+-------------------+
| version()         |
+-------------------+
| 2.3.2-percona-1.1 |
+-------------------+
1 row in set (0,00 sec)
```
In that case, suffix (raw_version[1]) is :  'percona'

Suffix should be a string value, and raw_version should have a maximum of 2 elements :
so suffix should be `percona-1.1`

I would suggest the following code  : 
```
def _version(cursor):
    cursor.execute("select version();")
    res = cursor.fetchone()

    # 2.2.0-72-ge14accd
    raw_version = res.get('version()').split('-',1)
    _version = raw_version[0].split('.')

    version = dict()
    version['full'] = res.get('version()')
    version['major'] = int(_version[0])
    version['minor'] = int(_version[1])
    version['release'] = int(_version[2])
    version['suffix'] = raw_version[1]

    return version

```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
mysql.py, line 56

##### ANSIBLE VERSION

```
ansible [core 2.11.8] 
  config file = /root/architecture_percona/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.7/dist-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.7.3 (default, Jan 22 2021, 20:04:44) [GCC 8.3.0]
  jinja version = 3.0.3
  libyaml = True
```

##### COLLECTION VERSION

```
# /usr/local/lib/python3.7/dist-packages/ansible_collections
Collection         Version
------------------ -------
community.proxysql 1.3.0  
```

##### CONFIGURATION

```
CACHE_PLUGIN(/root/architecture_percona/ansible.cfg) = jsonfile
CACHE_PLUGIN_CONNECTION(/root/architecture_percona/ansible.cfg) = cache
DEFAULT_BECOME(/root/architecture_percona/ansible.cfg) = True
DEFAULT_BECOME_ASK_PASS(/root/architecture_percona/ansible.cfg) = False
DEFAULT_BECOME_METHOD(/root/architecture_percona/ansible.cfg) = sudo
DEFAULT_BECOME_USER(/root/architecture_percona/ansible.cfg) = root
DEFAULT_CACHE_PLUGIN_PATH(/root/architecture_percona/ansible.cfg) = ['/usr/share/ansible/plugins/cache']
DEFAULT_GATHERING(/root/architecture_percona/ansible.cfg) = smart
DEFAULT_HOST_LIST(/root/architecture_percona/ansible.cfg) = ['/root/architecture_percona/hosts']
DEFAULT_PRIVATE_KEY_FILE(/root/architecture_percona/ansible.cfg) = /root/architecture_percona/rsa_ansible
DEFAULT_REMOTE_USER(/root/architecture_percona/ansible.cfg) = ansible
HOST_KEY_CHECKING(/root/architecture_percona/ansible.cfg) = False

```

##### OS / ENVIRONMENT

```
$ cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

##### STEPS TO REPRODUCE

In Percona's ProxySQL,  the `select version()` command returns something like : `2.3.2-percona-1.1`

```
- name: Ajout du noeud à la topologie proxysql (groupe readers)
  community.proxysql.proxysql_backend_servers:
    login_host: '{{clusterAlias}}'
    login_user: '{{ProxySQLAdmin}}'
    login_password: '{{ProxySQLAdminPass}}'
    hostname: '{{inventory_hostname}}'
    max_connections: 400
    max_replication_lag: 1
    status: ONLINE
    state: present
    load_to_runtime: True
    save_to_disk: True
```

##### ACTUAL RESULTS

```
The full traceback is:
Traceback (most recent call last):
  File "/home/ansible/.ansible/tmp/ansible-tmp-1645102377.3971581-48503-277139286733265/AnsiballZ_proxysql_backend_servers.py", line 100, in <module>
    _ansiballz_main()
  File "/home/ansible/.ansible/tmp/ansible-tmp-1645102377.3971581-48503-277139286733265/AnsiballZ_proxysql_backend_servers.py", line 92, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/ansible/.ansible/tmp/ansible-tmp-1645102377.3971581-48503-277139286733265/AnsiballZ_proxysql_backend_servers.py", line 41, in invoke_module
    run_name='__main__', alter_sys=True)
  File "/usr/lib/python3.7/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_community.proxysql.proxysql_backend_servers_payload_5zn4mrte/ansible_community.proxysql.proxysql_backend_servers_payload.zip/ansible_collections/community/proxysql/plugins/modules/proxysql_backend_servers.py", line 511, in <module>
  File "/tmp/ansible_community.proxysql.proxysql_backend_servers_payload_5zn4mrte/ansible_community.proxysql.proxysql_backend_servers_payload.zip/ansible_collections/community/proxysql/plugins/modules/proxysql_backend_servers.py", line 457, in main
  File "/tmp/ansible_community.proxysql.proxysql_backend_servers_payload_5zn4mrte/ansible_community.proxysql.proxysql_backend_servers_payload.zip/ansible_collections/community/proxysql/plugins/module_utils/mysql.py", line 123, in mysql_connect
  File "/tmp/ansible_community.proxysql.proxysql_backend_servers_payload_5zn4mrte/ansible_community.proxysql.proxysql_backend_servers_payload.zip/ansible_collections/community/proxysql/plugins/module_utils/mysql.py", line 56, in _version
ValueError: invalid literal for int() with base 10: 'percona'
fatal: [mysql8-test]: FAILED! => {
    "changed": false,
    "module_stderr": "Shared connection to mysql8-test closed.\r\n",
    "module_stdout": "Traceback (most recent call last):\r\n  File \"/home/ansible/.ansible/tmp/ansible-tmp-1645102377.3971581-48503-277139286733265/AnsiballZ_proxysql_backend_servers.py\", line 100, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/ansible/.ansible/tmp/ansible-tmp-1645102377.3971581-48503-277139286733265/AnsiballZ_proxysql_backend_servers.py\", line 92, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/ansible/.ansible/tmp/ansible-tmp-1645102377.3971581-48503-277139286733265/AnsiballZ_proxysql_backend_servers.py\", line 41, in invoke_module\r\n    run_name='__main__', alter_sys=True)\r\n  File \"/usr/lib/python3.7/runpy.py\", line 205, in run_module\r\n    return _run_module_code(code, init_globals, run_name, mod_spec)\r\n  File \"/usr/lib/python3.7/runpy.py\", line 96, in _run_module_code\r\n    mod_name, mod_spec, pkg_name, script_name)\r\n  File \"/usr/lib/python3.7/runpy.py\", line 85, in _run_code\r\n    exec(code, run_globals)\r\n  File \"/tmp/ansible_community.proxysql.proxysql_backend_servers_payload_5zn4mrte/ansible_community.proxysql.proxysql_backend_servers_payload.zip/ansible_collections/community/proxysql/plugins/modules/proxysql_backend_servers.py\", line 511, in <module>\r\n  File \"/tmp/ansible_community.proxysql.proxysql_backend_servers_payload_5zn4mrte/ansible_community.proxysql.proxysql_backend_servers_payload.zip/ansible_collections/community/proxysql/plugins/modules/proxysql_backend_servers.py\", line 457, in main\r\n  File \"/tmp/ansible_community.proxysql.proxysql_backend_servers_payload_5zn4mrte/ansible_community.proxysql.proxysql_backend_servers_payload.zip/ansible_collections/community/proxysql/plugins/module_utils/mysql.py\", line 123, in mysql_connect\r\n  File \"/tmp/ansible_community.proxysql.proxysql_backend_servers_payload_5zn4mrte/ansible_community.proxysql.proxysql_backend_servers_payload.zip/ansible_collections/community/proxysql/plugins/module_utils/mysql.py\", line 56, in _version\r\nValueError: invalid literal for int() with base 10: 'percona'\r\n",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

```

**Comment by markuman** [comment]
> I would suggest the following code :
> 
> ```
> def _version(cursor):
>     cursor.execute("select version();")
>     res = cursor.fetchone()
> 
>     # 2.2.0-72-ge14accd
>     raw_version = res.get('version()').split('-',1)
>     _version = raw_version[0].split('.')
> 
>     version = dict()
>     version['full'] = res.get('version()')
>     version['major'] = int(_version[0])
>     version['minor'] = int(_version[1])
>     version['release'] = int(_version[2])
>     version['suffix'] = raw_version[1]
> 
>     return version
> ```

nice. Can you provide a PR?

**Comment by Andersson007** [comment]
@PatrickBzh hi, thanks for the bug report!
Could you please submit a PR? See this short guide for details https://github.com/ansible/community-docs/blob/main/create_pr_quick_start_guide.rst
